"""Tests for the RFC 8785 JCS canonicalization subset.

All expected byte sequences below were generated by hand directly from the
normative rules of RFC 8785 (sections 3.2.2.2 string serialization, 3.2.2.3
number serialization, 3.2.2.4 literal names, 3.2.3 property sorting by UTF-16
code-unit order) — independently of the production serializer under test.
"""

from __future__ import annotations

import pytest

from quantara.jcs import JcsFloatRejected, canonicalize

VECTORS: list[tuple[object, str]] = [
    ({}, "{}"),
    ([], "[]"),
    (None, "null"),
    (True, "true"),
    (False, "false"),
    (0, "0"),
    (12345, "12345"),
    (-987, "-987"),
    ("simple", '"simple"'),
    ('quote"and\\slash', '"quote\\"and\\\\slash"'),
    (
        "line\nbreak\ttab\rret\bbackspace\fformfeed",
        '"line\\nbreak\\ttab\\rret\\bbackspace\\fformfeed"',
    ),
    ("\u0001\u001f", '"\\u0001\\u001f"'),
    # DEL and C1 controls are not escaped; only U+0000..U+001F are.
    ("keep \u007f and  literal", '"keep \u007f and  literal"'),
    (["b", 2, None, True], '["b",2,null,true]'),
    ({"b": 2, "a": 1}, '{"a":1,"b":2}'),
    # Property sort is UTF-16 code-unit order: 'A'(U+0041) < 'a'(U+0061) <
    # 'é'(U+00E9) < '€'(U+20AC) < '😀'(leading surrogate U+D83D).
    (
        {"€": 4, "é": 3, "a": 2, "A": 1, "😀": 5},
        '{"A":1,"a":2,"é":3,"€":4,"😀":5}',
    ),
    # Nested structures serialize depth-first with sorted object keys.
    (
        {"z": [{"k": [True, None]}, {}], "y": {}},
        '{"y":{},"z":[{"k":[true,null]},{}]}',
    ),
]


@pytest.mark.parametrize(("value", "expected"), VECTORS)
def test_canonicalize_fixed_vectors(value: object, expected: str) -> None:
    assert canonicalize(value) == expected


def test_output_is_utf8_round_trippable() -> None:
    payload = canonicalize({"é": "😀"})
    assert payload.encode("utf-8").decode("utf-8") == payload


@pytest.mark.parametrize("bad", [1.0, -0.5, 1e300])
def test_floats_are_rejected_at_top_level(bad: float) -> None:
    with pytest.raises(JcsFloatRejected):
        canonicalize(bad)


@pytest.mark.parametrize("bad", [1.0, -0.5, 1e-9, float("nan"), float("inf")])
def test_floats_are_rejected_anywhere_in_payload(bad: float) -> None:
    with pytest.raises(JcsFloatRejected):
        canonicalize({"ok": [1, "two", None, {"nested": bad}]})
